package ru.proghouse.cayenne.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ru.proghouse.cayenne.persistent.Painting;

/**
 * Class _Gallery was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Gallery extends CayenneDataObject {

    public static final String DATE_OF_BIRTH_PROPERTY = "dateOfBirth";
    public static final String NAME_PROPERTY = "name";
    public static final String PAINTING_GALLERY_PROPERTY = "paintingGallery";

    public static final String ID_PK_COLUMN = "ID";

    public void setDateOfBirth(Date dateOfBirth) {
        writeProperty(DATE_OF_BIRTH_PROPERTY, dateOfBirth);
    }
    public Date getDateOfBirth() {
        return (Date)readProperty(DATE_OF_BIRTH_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToPaintingGallery(Painting obj) {
        addToManyTarget(PAINTING_GALLERY_PROPERTY, obj, true);
    }
    public void removeFromPaintingGallery(Painting obj) {
        removeToManyTarget(PAINTING_GALLERY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Painting> getPaintingGallery() {
        return (List<Painting>)readProperty(PAINTING_GALLERY_PROPERTY);
    }


}
