package ru.proghouse.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

import ru.proghouse.cayenne.persistent.Artist;
import ru.proghouse.cayenne.persistent.Gallery;

/**
 * Class _Painting was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Painting extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ARTIST_PAINTING_PROPERTY = "artistPainting";
    public static final String GALLERY_PAINTING_PROPERTY = "galleryPainting";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setArtistPainting(Artist artistPainting) {
        setToOneTarget(ARTIST_PAINTING_PROPERTY, artistPainting, true);
    }

    public Artist getArtistPainting() {
        return (Artist)readProperty(ARTIST_PAINTING_PROPERTY);
    }


    public void setGalleryPainting(Gallery galleryPainting) {
        setToOneTarget(GALLERY_PAINTING_PROPERTY, galleryPainting, true);
    }

    public Gallery getGalleryPainting() {
        return (Gallery)readProperty(GALLERY_PAINTING_PROPERTY);
    }


}
